title: Team 1418
email: robotics1418@gmail.com
description: A FIRST Robotics team in Falls Church, VA.
baseurl: "" # Don't change this, this refers to the site's relative path, like /blog.
url: "http://1418.team"
twitter_username: Robotics1418
github_username: frc1418
facebook_username: robotics1418

# Build settings
sass:
    style: compressed
exclude:
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
    - vendor
    - vendor/cache
    - ruby
    - .bundle
include:
    - _pages
plugins:
    - octopress-autoprefixer
    - banner-locator
